### ISSUE TITLE
az openshift broken with clients > 2.4.0

### ISSUE THREAD

**Issue by novacain1** [Azure/OpenShift#183]
For ARO3, updating the azure-cli seems to break commands against the "openshift" resource.

$ az openshift list -o table
The resource type 'openShiftManagedClusters' could not be found in the namespace 'Microsoft.ContainerService' for api version '2019-10-27-preview'. The supported api-versions are '2019-04-30,2019-09-30-preview'.

This affects azure-cli versions 2.5.0 and 2.5.1.  Downgrading to 2.4.0 fixes the problem.

**Comment by olga-mir** [comment]
@novacain1 thanks for reporting this issue.
I wasn't able to reproduce this exact exact problem, however there is another issue with 2.5.x release which should be fixed here: https://github.com/Azure/azure-cli/pull/13315
I will keep an eye on when this gets released and will let you know.
The error that you are seeing probably caused by missing dependencies. I am using yum to upgrade the cli and I haven't seen this problem. How do you upgrade azure-cli? can you paste output of `az version` if you see this error again?

**Comment by vincepower** [comment]
Well, this is the problem I'm having with 2.5.1 related to openshift and downgrading 2.4.0 fixed it.

`
[rhpds@r1 ansible]$ az version
{
  "azure-cli": "2.5.1",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.5.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "aro": "1.0.0"
  }
}
[rhpds@r1 ansible]$  az openshift create -g vptest -n vptest
Please make sure your subscription is whitelisted to use this service. https://aka.ms/openshift/managed
[rhpds@r1 ansible]$ az openshift list -o table
The resource type 'openShiftManagedClusters' could not be found in the namespace 'Microsoft.ContainerService' for api version '2019-                                                                                                                                                                                         10-27-preview'. The supported api-versions are '2019-04-30,2019-09-30-preview'.
[rhpds@r1 ansible]$ sudo yum downgrade azure-cli-2.4.0
Updating Subscription Management repositories.
Last metadata expiration check: 0:50:30 ago on Mon 18 May 2020 12:23:37 PM EDT.
Dependencies resolved.
====================================================================================================================================
 Package                        Architecture                Version                            Repository                      Size
====================================================================================================================================
Downgrading:
 azure-cli                      x86_64                      2.4.0-1.el7                        azure-cli                       43 M

Transaction Summary
====================================================================================================================================
Downgrade  1 Package

Total download size: 43 M
Is this ok [y/N]: y
Downloading Packages:
azure-cli-2.4.0-1.el7.x86_64.rpm                                                                     37 MB/s |  43 MB     00:01
------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                36 MB/s |  43 MB     00:01
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                            1/1
  Downgrading      : azure-cli-2.4.0-1.el7.x86_64                                                                               1/2
  Cleanup          : azure-cli-2.5.1-1.el7.x86_64                                                                               2/2
  Running scriptlet: azure-cli-2.5.1-1.el7.x86_64                                                                               2/2
  Verifying        : azure-cli-2.4.0-1.el7.x86_64                                                                               1/2
  Verifying        : azure-cli-2.5.1-1.el7.x86_64                                                                               2/2
Installed products updated.

Downgraded:
  azure-cli-2.4.0-1.el7.x86_64

Complete!
[rhpds@r1 ansible]$ az openshift create -n vptest -g vptest
 - Running ..
`

**Comment by novacain1** [comment]
@asinn826 fyi...

**Comment by olga-mir** [comment]
Thank you for the details @vincepower 
I am wondering if this is something specific to a certain region.  

There is another failure in 2.5.x that I have fixed, but it has not been released yet, but I doubt that it will have any effect on that particular failure that you are facing.

I've noticed in a few places `openshiftmanagedClusters` is used and in some `openShiftManagedClusters` is used. I will try to run my fix again in another region and see if I can reproduce this failure, because it does work for me in `eastus2`

**Comment by vincepower** [comment]
well, 2.6.0 did not seem to fix it and region doesn't even come into play with "az openshift list"

any suggestions and I'm more than willing to test

```
[rhpds@r1 ~]$ az --version
azure-cli                          2.6.0

command-modules-nspkg              2.0.3
core                               2.6.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
aro                                1.0.0

Python location '/usr/bin/python3'
Extensions directory '/home/rhpds/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Dec  5 2019, 15:45:45)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Please let us know how we are doing: https://aka.ms/clihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
[rhpds@r1 ~]$ az logout
[rhpds@r1 ~]$ rm -rf .azure/
[rhpds@r1 ~]$ az login --service-principal -t abcdef -u username -p 'password'
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "abcdef ",
    "id": "ghijkl",
    "isDefault": true,
    "managedByTenants": [
      {
        "tenantId": "mnopqr"
      }
    ],
    "name": "RHPDS Subscription",
    "state": "Enabled",
    "tenantId": "abcdef",
    "user": {
      "name": "username",
      "type": "servicePrincipal"
    }
  }
]
[rhpds@r1 ~]$ az openshift list -o table
The resource type 'openShiftManagedClusters' could not be found in the namespace 'Microsoft.ContainerService' for api version '2019-10-27-preview'. The supported api-versions are '2019-04-30,2019-09-30-preview'.
```

**Comment by olga-mir** [comment]
@vincepower thank you for the detailed reports and the support. Unfortunately this is expected behavior for most of the customers except those white listed for private cluster feature on v3. This will remain broken until https://github.com/Azure/azure-cli/pull/13618 is merged and released. In the meanwhile we encourage customers to use v4 if possible otherwise use cli version < 2.4.x

**Comment by sakthi-vetrivel** [comment]
@vincepower Thanks for your feedback - this is now resolved.
